# Generated by Django 3.0.8 on 2020-07-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leave_type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('leave_description', models.CharField(max_length=300)),
                ('total_leaves_given', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('leave_type', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remark', models.CharField(max_length=300)),
                ('approval', models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('R', 'REJECTED')], default='P', max_length=1)),
                ('hr_remark', models.CharField(default='', max_length=100)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.Leave')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
